# These combinations of prompts show as placeholders for the prompt search on the main YourNextAlbum streamlit interface.

placeholder_examples = [
    "atmospheric electronic",
    "high-energy rock for workouts",
    "calm jazz for studying",
    "melancholic indie folk",
    "upbeat dance music for parties",
    "dark ambient soundscapes",
    "soulful R&B with smooth vocals",
    "experimental hip-hop",
    "dreamy shoegaze guitars",
    "aggressive punk energy",
    "romantic classical piano",
    "funky bass-driven grooves",
    "sad songs for rainy days",
    "uplifting anthems",
    "psychedelic rock jams",
    "nostalgic 80s synth-pop",
    "intense metal with heavy riffs",
    "chill lo-fi beats",
    "emotional singer-songwriter",
    "groovy disco vibes",
    "introspective bedroom pop",
    "epic orchestral soundtracks",
    "raw garage rock",
    "smooth bossa nova",
    "energetic ska-punk",
    "meditative new age",
    "gritty blues with soul",
    "futuristic synthwave",
    "powerful protest songs",
    "trippy psych-folk",
    "minimal techno for focus",
    "explosive noise rock",
    "jazzy hip-hop instrumentals",
    "haunting gothic post-punk",
    "feel-good summer pop",
    "cinematic post-rock",
    "intimate acoustic ballads",
    "funk-infused rock",
    "ethereal vocal harmonies",
    "driving country rock",
    "catchy power pop",
    "spiritual gospel choirs",
    "dynamic progressive metal",
    "laid-back reggae rhythms",
    "complex math rock",
    "soul-stirring blues rock",
    "hypnotic trance music",
    "raw lo-fi indie rock",
    "uplifting worship music",
    "cinematic electronic",
    "intense hardcore punk",
    "melodic death metal",
    "smooth jazz fusion",
    "ambient drone music",
    "funky soul classics",
    "darkwave synth-pop",
    "upbeat indie pop",
    "emotional post-hardcore",
    "groovy funk rock",
    "dreamy ambient pop",
    "aggressive thrash metal",
    "chillwave synths",
    "introspective folk rock",
    "epic symphonic metal",
    "raw punk rock anthems",
    "smooth R&B ballads",
    "energetic pop punk",
    "meditative ambient soundscapes",
    "gritty alternative rock",
    "futuristic electronic beats",
    "powerful rock ballads",
    "trippy psychedelic rock",
    "minimalist classical compositions",
    "explosive hard rock",
    "jazzy soul grooves",
    "haunting indie folk",
    "feel-good pop rock",
    "cinematic orchestral pieces",
    "intimate acoustic songs",
    "funky disco hits",
    "ethereal dream pop",
    "driving rock anthems",
    "catchy indie rock tunes",
    "spiritual new age music",
    "dynamic jazz improvisations",
    "laid-back soft rock",
    "complex progressive rock",
    "soul-stirring ballads",
    "hypnotic electronic music",
    "raw garage punk",
    "uplifting pop anthems",
    "cinematic film scores",
    "intense metalcore",
    "melodic indie pop",
    "smooth jazz standards",
    "ambient chillout music",
    "funky rhythm and blues",
    "dark ambient soundtracks",
    "upbeat dance-pop",
    "emotional acoustic ballads",
    "groovy funk jams",
    "dreamy shoegaze soundscapes",
    "aggressive punk rock",
    "chill lo-fi hip-hop",
    "introspective singer-songwriter",
    "epic orchestral arrangements",
    "raw blues rock",
    "smooth bossa nova tunes",
    "energetic ska rhythms",
    "meditative new age soundscapes",
    "gritty blues classics",
    "futuristic synth-pop",
    "powerful protest anthems",
    "trippy psych-rock",
    "minimal techno beats",
    "explosive noise punk",
    "jazzy hip-hop beats",
    "haunting gothic rock",
    "feel-good summer hits",
    "cinematic post-rock pieces",
    "intimate acoustic performances",
    "funk-infused grooves",
    "ethereal vocal layers",
]