# Random placeholder examples
placeholder_examples = [
    "atmospheric electronic",
    "high-energy rock for workouts",
    "calm jazz for studying",
    "melancholic indie folk",
    "upbeat dance music for parties",
    "dark ambient soundscapes",
    "soulful R&B with smooth vocals",
    "experimental hip-hop",
    "dreamy shoegaze guitars",
    "aggressive punk energy",
    "romantic classical piano",
    "funky bass-driven grooves",
    "sad songs for rainy days",
    "uplifting anthems",
    "psychedelic rock jams",
    "nostalgic 80s synth-pop",
    "intense metal with heavy riffs",
    "chill lo-fi beats",
    "emotional singer-songwriter",
    "groovy disco vibes",
    "introspective bedroom pop",
    "epic orchestral soundtracks",
    "raw garage rock",
    "smooth bossa nova",
    "energetic ska-punk",
    "meditative new age",
    "gritty blues with soul",
    "futuristic synthwave",
    "powerful protest songs",
    "trippy psych-folk",
    "minimal techno for focus",
    "explosive noise rock",
    "jazzy hip-hop instrumentals",
    "haunting gothic post-punk",
    "feel-good summer pop",
    "cinematic post-rock",
    "intimate acoustic ballads",
    "funk-infused rock",
    "ethereal vocal harmonies",
    "driving country rock",
    "catchy power pop",
    "spiritual gospel choirs",
    "dynamic progressive metal",
    "laid-back reggae rhythms",
    "complex math rock",
    "soul-stirring blues rock",
    "hypnotic trance music",
    "raw lo-fi indie rock",
    "uplifting worship music",
    "cinematic electronic",
    "intense hardcore punk",
    "melodic death metal",
    "smooth jazz fusion",
    "ambient drone music",
    "funky soul classics",
    "darkwave synth-pop",
]